using System;
using System.Collections.Generic;
using System.Text;

namespace Forms.Resources.localization
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class loc
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal loc()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forms.Resources.localization.loc", typeof(loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must fill all fields.
        /// </summary>
        public static string Auth_Error_EmptyField
        {
            get
            {
                return ResourceManager.GetString("Auth_Error_EmptyField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User/Password invalid.
        /// </summary>
        public static string Auth_Error_InvalidCred
        {
            get
            {
                return ResourceManager.GetString("Auth_Error_InvalidCred", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check your network connection.
        /// </summary>
        public static string Auth_Error_NotConnected
        {
            get
            {
                return ResourceManager.GetString("Auth_Error_NotConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credentials too old.
        /// </summary>
        public static string Auth_Error_OfflineAuth
        {
            get
            {
                return ResourceManager.GetString("Auth_Error_OfflineAuth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string Auth_Error_Server
        {
            get
            {
                return ResourceManager.GetString("Auth_Error_Server", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Auth_Title
        {
            get
            {
                return ResourceManager.GetString("Auth_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Button_Validate
        {
            get
            {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Label_Hello
        {
            get
            {
                return ResourceManager.GetString("Label_Hello", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password
        {
            get
            {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Label_User
        {
            get
            {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect
        {
            get
            {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to App_Name.
        /// </summary>
        public static string App_Name
        {
            get
            {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login_Label.
        /// </summary>
        public static string Login_Label
        {
            get
            {
                return ResourceManager.GetString("Login_Label", resourceCulture);
            }
        }
    }
}
